electrum: build: bump ubuntu dockers to 22.04
Summary:
This gives us OpenSSL 3 which is needed to bump the cryptography python lib in a following commit.
Note that this does not affect the OpenSSL version built by the `make_openssl` script (1.1.1t) and used by `make_libevent`

libevent needs to be bumped from 2.1.11-stable to >=2.1.12-stable because the previous one used a `#include <sys/sysctl.h>` that was deprecated in glibc, and is no longer shipped in Ubuntu 22.04’s glibc.

Depends on D20732

Test Plan:
```
contrib/build-linux/appimage/build.sh
contrib/build-linux/srcdist-docker/build.sh
contrib/build-wine/build.sh
```

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Differential Revision: https://reviews.bitcoinabc.org/D20733

diff --git a/electrum/contrib/make_libevent b/electrum/contrib/make_libevent
--- a/electrum/contrib/make_libevent
+++ b/electrum/contrib/make_libevent
@@ -5,7 +5,7 @@ set -e
 here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
 . "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)
 
-setup_pkg "libevent" "https://github.com/libevent/libevent.git" "4c908dde58ef780eeefcc9df4db3063ca62ea862"
+setup_pkg "libevent" "https://github.com/libevent/libevent.git" "release-2.1.13-stable"
 
 if ! [ -x configure ] ; then
     ./autogen.sh || fail "Could not configure $pkgname"
@@ -19,8 +19,11 @@ if ! [ -r config.status ] ; then
         --with-pic \
         --disable-samples \
         --disable-libevent-regress \
-        CPPFLAGS=-I"$parentbuilddir"/openssl/dist \
-        LDFLAGS=-L"$parentbuilddir"/openssl/dist || fail "Could not configure $pkgname"
+        CPPFLAGS="-I$parentbuilddir/openssl/dist/include" \
+        LDFLAGS="-L$parentbuilddir/openssl/dist/lib" \
+        OPENSSL_CFLAGS="-I$parentbuilddir/openssl/dist/include" \
+        OPENSSL_LIBS="-L$parentbuilddir/openssl/dist/lib -lssl -lcrypto" \
+        PKG_CONFIG_PATH="$parentbuilddir/openssl/dist/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}" || fail "Could not configure $pkgname"
 fi
 make -j$WORKER_COUNT || fail "Could not build $pkgname"
 make install || fail "Could not install $pkgname"
