[electrum] make the release scripts build the tor binary
Summary:
This is a partial revert of https://github.com/Bitcoin-ABC/ElectrumABC/commit/14f115f5fbc72d4e69e84ba1c7f22782ebd11966

But we still don't want to bundle the tor binary with the release, we just want to produce it as an artifact, so we can generate a tor executable that can be made available for easy downloaded by users via the Electrum ABC network settings UI. Whenever this convenience tor needs to be updated, we can use the release scripts to generate it and then upload it to wherever tor_downloader.py expects to find it (currently https://github.com/PiRK/Electrum-ABC-Build-Tools)

Make the `make_tor` script copy the executable to `dist/`, together with the other release files, instead of putting it inside the Electrum ABC package where it used to be before we stopped including it.

The MacOS build does not run in a docker, so we can just manually run `make_openssl && make_libevent && make_zlib && make_tor` on the same host used to build the release. No need to do it for every the release.

Update also make_openssl build a 64 bits release. This was missed in D19530 because there was no compelling reason to update the tor binaries at the time.
This change is a partial backport of https://github.com/Electron-Cash/Electron-Cash/commit/21a41703894beca809cabb69b784f2a68214e67a

Depends on D20211

Test Plan:
```
contrib/make-clean
contrib/build-linux/appimage/build.sh
ls dist/
contrib/make-clean
contrib/build-wine/build.sh
ls dist/
```

Reviewers: #bitcoin_abc, bytesofman

Reviewed By: #bitcoin_abc, bytesofman

Subscribers: bytesofman

Differential Revision: https://reviews.bitcoinabc.org/D20212

diff --git a/electrum/contrib/make_tor b/electrum/contrib/make_tor
--- a/electrum/contrib/make_tor
+++ b/electrum/contrib/make_tor
@@ -46,9 +46,9 @@ if [ "$BUILD_TYPE" = "wine" ] ; then
     binary="tor.exe"
 fi
 host_strip "$pkgbuilddir/dist/bin/$binary"
-mkdir -p "$here/../electrumabc/tor/bin"
-cp -fpv "$pkgbuilddir/dist/bin/$binary" "$here/../electrumabc/tor/bin/." || fail "Could not copy the $pkgname binary to its destination"
+mkdir -p "$DISTDIR"
+cp -fpv "$pkgbuilddir/dist/bin/$binary" "$DISTDIR/." || fail "Could not copy the $pkgname binary to its destination"
 $SHA256_PROG "$pkgbuilddir/dist/bin/$binary"
-info "$binary has been placed in the 'electrumabc' folder."
+info "$binary has been placed in the 'dist' folder."
 popd_pkg
 rm -Rf "$here"/tor
